"use client";
import Link from "next/link";
import { ActivityCard } from "@/components/activity-card";
import { ActivityTable } from "@/components/activity-table";
import { SummaryTile } from "@/components/summary-tile";
import { SystemIcon } from "@/components/system-icon";
import { canViewActivity, useSimulatedActivities } from "@/lib/activity-simulation";
import type { Role } from "@/lib/roles";
export function ActivityDashboard({ role }: { role: Role }) { const activities = useSimulatedActivities().filter((item) => !item.deletedAt && canViewActivity(item, role)); const count = (status: string) => activities.filter((item) => item.status === status).length; return <><section className="grid grid-cols-3 gap-2 lg:gap-4"><SummaryTile detail="Por iniciar" icon={<SystemIcon className="size-6" name="calendar" />} iconClassName="bg-amber text-ink" label="Programadas" value={count("Programada")} /><SummaryTile detail="Trabajo activo" icon={<SystemIcon className="size-6" name="progress" />} iconClassName="bg-turquoise text-white" label="En proceso" value={count("En proceso")} /><SummaryTile detail="Con material" icon={<SystemIcon className="size-6" name="complete" />} iconClassName="bg-blue text-white" label="Entregadas" value={count("Entregada")} /></section><section className="space-y-2"><div className="flex items-center justify-between"><h2 className="text-sm font-bold uppercase tracking-[0.1em]">Trabajo diario</h2><span className="text-xs text-ink-muted">{activities.length} actividades</span></div>{activities.length ? <><div className="space-y-2 lg:hidden">{activities.map((item) => <ActivityCard activity={item} key={item.id} showResponsible={role.seesAllActivities} />)}</div><ActivityTable activities={activities} showResponsible={role.seesAllActivities} /></> : <p className="rounded-[5px] border border-line bg-panel p-6 text-center text-sm text-ink-muted">Todavía no hay actividades para esta cuenta.</p>}</section>{role.id === "operario" && <Link className="sticky bottom-[4.75rem] flex min-h-12 items-center justify-center rounded-[5px] border border-amber bg-amber px-5 text-sm font-bold lg:static lg:ml-auto lg:w-fit" href="/actividades/nueva">＋ Nueva actividad</Link>}</>; }
