"use client";

import { useState } from "react";
import { BursonStatusPill, bursonStatuses } from "@/components/burson-status-pill";
import { Button } from "@/components/button";
import { Card } from "@/components/card";
import { addBursonComment, deleteBursonComment, deleteBursonRequest, editBursonComment, type BursonFields, type BursonRequest, upsertBursonRequest, useBursonRequests } from "@/lib/burson-store";
import type { Role } from "@/lib/roles";

const control = "min-h-11 w-full rounded-[5px] border border-line bg-panel px-3 py-2 text-sm";
const emptyFields: BursonFields = { request: "", date: "", responsible: "", material: "", status: "Solicitado", rhinoPending: "", bursonPending: "", deliveryDate: "", approvalDate: "" };
function fieldsOf(item: BursonRequest): BursonFields { return { request: item.request, date: item.date, responsible: item.responsible, material: item.material, status: item.status, rhinoPending: item.rhinoPending, bursonPending: item.bursonPending, deliveryDate: item.deliveryDate, approvalDate: item.approvalDate }; }
function formatDate(value: string) { if (!value) return "Sin fecha"; const date = new Date(`${value.length === 10 ? `${value}T12:00:00` : value}`); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("es-PE", { dateStyle: "medium" }).format(date); }

export function BursonDashboard({ role }: { role: Role }) {
  const stored = useBursonRequests(); const requests = stored.filter((item) => !item.deletedAt); const canWrite = role.writesBurson;
  const [formOpen, setFormOpen] = useState(false); const [editingId, setEditingId] = useState<string | null>(null); const [fields, setFields] = useState<BursonFields>(emptyFields);
  const [deletingId, setDeletingId] = useState<string | null>(null); const [notice, setNotice] = useState("");
  const [commentDrafts, setCommentDrafts] = useState<Record<string, string>>({}); const [editingComment, setEditingComment] = useState<{ requestId: string; commentId: string } | null>(null); const [commentText, setCommentText] = useState(""); const [deletingComment, setDeletingComment] = useState<{ requestId: string; commentId: string } | null>(null);
  const rhinoCount = requests.filter((item) => item.rhinoPending.trim() && item.rhinoPending !== "Sin pendientes").length; const bursonCount = requests.filter((item) => item.bursonPending.trim() && item.bursonPending !== "Sin pendientes").length;
  function setField(name: keyof BursonFields, value: string) { setFields((current) => ({ ...current, [name]: value })); }
  function closeForm() { setFormOpen(false); setEditingId(null); setFields(emptyFields); }
  function saveRequest() { const result = upsertBursonRequest(window.localStorage, fields, role.label, editingId ?? undefined); setNotice(result.ok ? editingId ? "Solicitud actualizada." : "Solicitud creada." : result.error); if (result.ok) closeForm(); }
  function beginEdit(item: BursonRequest) { setEditingId(item.id); setFields(fieldsOf(item)); setFormOpen(true); }
  function addComment(requestId: string) { const result = addBursonComment(window.localStorage, requestId, commentDrafts[requestId] ?? "", role.label); setNotice(result.ok ? "Comentario agregado." : result.error); if (result.ok) setCommentDrafts((current) => ({ ...current, [requestId]: "" })); }
  function saveComment() { if (!editingComment) return; const result = editBursonComment(window.localStorage, editingComment.requestId, editingComment.commentId, commentText, role.label); setNotice(result.ok ? "Comentario actualizado." : result.error); if (result.ok) setEditingComment(null); }

  return <>
    {notice && <p aria-live="polite" className="rounded-[5px] border border-blue bg-blue/10 p-3 text-sm font-bold">{notice}</p>}
    {!canWrite && <aside className="rounded-[5px] border border-blue bg-blue/10 p-3 text-sm font-bold">Vista de solo lectura. Rhino administra solicitudes, estados y pendientes.</aside>}
    <section aria-label="Resumen de pendientes" className="grid grid-cols-2 gap-2"><Card className="border-blue p-3"><span className="text-[0.6875rem] font-bold uppercase tracking-[0.12em] text-blue">Pendientes de Rhino</span><strong className="mt-2 block text-3xl tabular-nums">{rhinoCount}</strong><span className="text-xs text-ink-muted">Requieren acción interna</span></Card><Card className="border-amber p-3"><span className="text-[0.6875rem] font-bold uppercase tracking-[0.12em]">Pendientes de Burson</span><strong className="mt-2 block text-3xl tabular-nums">{bursonCount}</strong><span className="text-xs text-ink-muted">Esperando respuesta</span></Card></section>
    {canWrite && !formOpen && <Button className="w-full lg:ml-auto lg:w-fit" onClick={() => setFormOpen(true)}>＋ Nueva solicitud</Button>}
    {canWrite && formOpen && <Card className="space-y-4 border-blue p-4"><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-blue">{editingId ? "Editar solicitud" : "Nueva solicitud"}</p><h2 className="mt-1 text-lg font-bold">Coordinación con Burson</h2></div><div className="grid gap-3 lg:grid-cols-2"><label className="text-sm font-bold lg:col-span-2">Solicitud<input className={`${control} mt-2`} onChange={(event) => setField("request", event.target.value)} value={fields.request} /></label><label className="text-sm font-bold">Fecha<input className={`${control} mt-2`} onChange={(event) => setField("date", event.target.value)} type="date" value={fields.date} /></label><label className="text-sm font-bold">Estado<select className={`${control} mt-2`} onChange={(event) => setField("status", event.target.value)} value={fields.status}>{bursonStatuses.map((status) => <option key={status}>{status}</option>)}</select></label><label className="text-sm font-bold">Responsable<input className={`${control} mt-2`} onChange={(event) => setField("responsible", event.target.value)} value={fields.responsible} /></label><label className="text-sm font-bold">Material solicitado<input className={`${control} mt-2`} onChange={(event) => setField("material", event.target.value)} value={fields.material} /></label><label className="text-sm font-bold">Pendientes de Rhino<textarea className={`${control} mt-2 min-h-20`} onChange={(event) => setField("rhinoPending", event.target.value)} value={fields.rhinoPending} /></label><label className="text-sm font-bold">Pendientes de Burson<textarea className={`${control} mt-2 min-h-20`} onChange={(event) => setField("bursonPending", event.target.value)} value={fields.bursonPending} /></label><label className="text-sm font-bold">Fecha de entrega<input className={`${control} mt-2`} onChange={(event) => setField("deliveryDate", event.target.value)} type="date" value={fields.deliveryDate} /></label><label className="text-sm font-bold">Fecha de aprobación<input className={`${control} mt-2`} onChange={(event) => setField("approvalDate", event.target.value)} type="date" value={fields.approvalDate} /></label></div><div className="grid grid-cols-2 gap-2"><Button onClick={closeForm} variant="secondary">Cancelar</Button><Button onClick={saveRequest}>Guardar</Button></div></Card>}
    <section aria-labelledby="requests-title" className="space-y-2"><div className="flex items-end justify-between gap-3"><h2 className="text-sm font-bold uppercase tracking-[0.1em]" id="requests-title">Solicitudes</h2><span className="text-xs text-ink-muted">{requests.length} visibles</span></div><div className="grid gap-3 lg:grid-cols-2">{requests.map((item) => <Card className="p-3" key={item.id}><div className="flex items-start justify-between gap-3"><div><p className="text-[0.6875rem] font-bold uppercase tracking-[0.12em] text-blue">{formatDate(item.date)}</p><h3 className="mt-1 text-sm font-bold">{item.request}</h3></div><BursonStatusPill status={item.status} /></div><dl className="mt-3 grid grid-cols-2 gap-2 border-t border-line pt-3 text-xs"><div><dt className="font-bold">Responsable de Rhino</dt><dd className="mt-1 text-ink-muted">{item.responsible}</dd></div><div><dt className="font-bold">Material solicitado</dt><dd className="mt-1 text-ink-muted">{item.material}</dd></div><div><dt className="font-bold">Entrega</dt><dd className="mt-1 text-ink-muted">{formatDate(item.deliveryDate)}</dd></div><div><dt className="font-bold">Aprobación</dt><dd className="mt-1 text-ink-muted">{formatDate(item.approvalDate)}</dd></div></dl><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-[5px] border border-blue bg-blue/5 p-2"><p className="text-[0.625rem] font-bold uppercase text-blue">Rhino debe</p><p className="mt-1 text-xs font-semibold">{item.rhinoPending || "Sin pendientes"}</p></div><div className="rounded-[5px] border border-amber bg-amber/10 p-2"><p className="text-[0.625rem] font-bold uppercase">Burson debe</p><p className="mt-1 text-xs font-semibold">{item.bursonPending || "Sin pendientes"}</p></div></div>
        <details className="mt-3 border-t border-line pt-3"><summary className="cursor-pointer text-xs font-bold text-blue">Comentarios e historial</summary><div className="mt-3 space-y-2">{item.comments.filter((comment) => !comment.deletedAt).map((comment) => <div className="rounded-[5px] bg-panel-secondary p-2 text-sm" key={comment.id}>{editingComment?.commentId === comment.id ? <div className="space-y-2"><textarea aria-label="Editar comentario Burson" className={`${control} min-h-20`} onChange={(event) => setCommentText(event.target.value)} value={commentText} /><div className="grid grid-cols-2 gap-2"><Button onClick={() => setEditingComment(null)} variant="secondary">Cancelar</Button><Button onClick={saveComment}>Guardar</Button></div></div> : deletingComment?.commentId === comment.id ? <div><p className="font-bold text-red">¿Eliminar comentario?</p><div className="mt-2 grid grid-cols-2 gap-2"><Button onClick={() => setDeletingComment(null)} variant="secondary">Conservar</Button><Button onClick={() => { const result = deleteBursonComment(window.localStorage, item.id, comment.id, role.label); setNotice(result.ok ? "Comentario eliminado." : result.error); setDeletingComment(null); }}>Eliminar</Button></div></div> : <><p>{comment.text} {comment.editedAt && <small className="font-bold text-ink-muted">(Editado)</small>}</p><p className="mt-1 text-[0.6875rem] text-ink-muted">{comment.author} · {formatDate(comment.createdAt)}</p>{canWrite && <div className="mt-1 flex gap-3"><button className="text-xs font-bold text-blue underline" onClick={() => { setEditingComment({ requestId: item.id, commentId: comment.id }); setCommentText(comment.text); }} type="button">Editar</button><button className="text-xs font-bold text-red underline" onClick={() => setDeletingComment({ requestId: item.id, commentId: comment.id })} type="button">Eliminar</button></div>}</>}</div>)}{canWrite && <div className="space-y-2"><textarea className={`${control} min-h-20`} onChange={(event) => setCommentDrafts((current) => ({ ...current, [item.id]: event.target.value }))} placeholder="Añadir comentario" value={commentDrafts[item.id] ?? ""} /><Button className="w-full" onClick={() => addComment(item.id)} variant="secondary">Agregar comentario</Button></div>}<div className="border-t border-line pt-2">{item.history.map((entry, index) => <p className="text-xs text-ink-muted" key={`${entry.moment}-${index}`}><strong className="text-ink">{entry.status}</strong> · {entry.actor} · {formatDate(entry.moment)}</p>)}</div></div></details>
        {canWrite && (deletingId === item.id ? <div className="mt-3 rounded-[5px] border border-red bg-red/5 p-3"><p className="text-sm font-bold text-red">¿Eliminar esta solicitud?</p><div className="mt-2 grid grid-cols-2 gap-2"><Button onClick={() => setDeletingId(null)} variant="secondary">Conservar</Button><Button onClick={() => { const result = deleteBursonRequest(window.localStorage, item.id, role.label); setNotice(result.ok ? "Solicitud eliminada." : result.error); setDeletingId(null); }}>Eliminar</Button></div></div> : <div className="mt-3 grid grid-cols-2 gap-2 border-t border-line pt-3"><Button onClick={() => beginEdit(item)} variant="secondary">Editar</Button><button className="min-h-11 rounded-[5px] text-sm font-bold text-red underline" onClick={() => setDeletingId(item.id)} type="button">Eliminar</button></div>)}
      </Card>)}</div></section>
  </>;
}
