"use client";
import Link from "next/link";
import { useState } from "react";
import { LoginForm } from "@/app/acceso/login-form";
import { Avatar } from "@/components/avatar";
import { Card } from "@/components/card";
import { SystemIcon } from "@/components/system-icon";
import { defaultAccounts } from "@/lib/accounts";
import { roles } from "@/lib/roles";

const activityCounts: Record<string, number> = { "account-admin": 34, "account-ana": 12, "account-carlos": 7, "account-burson": 6, "account-luis": 9 };
const accessAccounts = defaultAccounts.map((item) => ({ roleId: item.roleId, user: item.username, accountId: item.id, name: item.name, bursonLinked: item.bursonLinked }));
const testUsers = accessAccounts;

export default function AccessPage() {
  const [selected, setSelected] = useState(accessAccounts[0]);
  return <main className="technical-surface relative min-h-screen overflow-x-hidden px-3 py-5 text-white sm:px-6 lg:px-10 lg:py-7">
    <Link className="relative z-10 inline-flex min-h-10 items-center gap-2 text-xs text-white/80 transition hover:text-cyan" href="/"><span className="grid size-7 place-items-center rounded-full border border-white/20">▣</span><span>Acceso mediante contraseña</span></Link>
    <header className="relative z-10 mx-auto mt-5 max-w-4xl text-center lg:mt-4"><h1 className="brand-condensed text-[2.45rem] leading-none drop-shadow-[0_4px_10px_rgba(0,0,0,.65)] sm:text-5xl lg:text-[4.1rem]">CONTROL DE ACTIVIDADES</h1><p className="mt-3 text-xs font-extrabold tracking-[0.25em] text-cyan sm:text-lg">RHINO AUDIOVISUALES</p><span className="mx-auto mt-3 block h-[3px] w-12 bg-lime shadow-[0_0_14px_rgba(132,214,0,.5)]" /><p className="mt-3 text-sm text-white/70">Gestión integral del equipo audiovisual</p><span className="mt-4 inline-flex items-center gap-3 rounded-full border border-white/30 bg-white/[.025] px-6 py-2.5 text-sm shadow-[inset_0_0_20px_rgba(17,183,201,.04)]"><SystemIcon className="size-4 text-cyan" name="calendar" />Agosto 2026 <small>⌄</small></span></header>
    <section aria-labelledby="test-users-title" className="relative z-10 mx-auto mt-6 max-w-7xl pb-[31rem] lg:mt-5 lg:pb-10"><h2 className="sr-only" id="test-users-title">Cuentas de acceso</h2><ul className="space-y-1.5">{testUsers.map((account) => { const initials = account.name.split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase(); const active = selected.accountId === account.accountId; return <li key={account.accountId}><Card className={`grid min-h-[4.8rem] grid-cols-[1fr_auto] items-center gap-3 px-4 py-2.5 text-ink transition duration-200 lg:grid-cols-[minmax(16rem,1.25fr)_9rem_8rem_14rem_8.5rem] ${active ? "border-2 border-cyan shadow-[0_0_0_1px_rgba(17,183,201,.14),var(--shadow-2)]" : "hover:-translate-y-px hover:border-cyan/50 hover:shadow-[var(--shadow-2)]"}`}><div className="flex min-w-0 items-center gap-3"><Avatar initials={initials} /><span className="min-w-0"><strong className="display-title block truncate text-base">{account.name}</strong><small className="block truncate text-ink-muted">{roles[account.roleId].label}{account.bursonLinked ? " especial · encargos Burson" : ""}</small></span></div><span className="hidden items-center gap-2 rounded-lg bg-green/10 px-3 py-2 text-xs font-bold text-green lg:flex"><i className="size-2 rounded-full bg-green" />Activo</span><span className="hidden border-l border-line pl-4 lg:block"><b className="display-title block text-xl tabular-nums">{activityCounts[account.accountId] ?? 0}</b><small className="text-[0.625rem] text-ink-muted">actividades</small></span><span className="hidden border-l border-line pl-4 text-[0.625rem] text-ink-muted lg:block">◷ &nbsp; Última actualización<br /><b className="font-mono font-normal">20/08/2026 · 16:45</b></span><button className="action-surface min-h-10 rounded-md px-4 text-xs font-extrabold text-[#173000] shadow-[0_6px_14px_rgba(95,170,0,.2)]" onClick={() => setSelected(account)} type="button">Ingresar&nbsp; ›</button></Card></li>; })}</ul></section>
    <div aria-hidden="true" className="pointer-events-none fixed inset-0 z-20 hidden bg-night/62 backdrop-blur-[1px] lg:block" />
    <Card className="absolute inset-x-3 bottom-6 z-30 mx-auto max-w-[25.5rem] p-5 text-ink shadow-[var(--shadow-3)] sm:inset-x-6 lg:fixed lg:bottom-auto lg:left-1/2 lg:right-auto lg:top-[56%] lg:w-[25.5rem] lg:-translate-x-1/2 lg:-translate-y-1/2 lg:p-6"><div className="text-center"><span className="mx-auto grid size-16 place-items-center rounded-full border-[5px] border-cyan/10 bg-gradient-to-br from-cyan to-[#078ca2] text-white shadow-[0_7px_18px_rgba(0,142,164,.24)]"><SystemIcon className="size-7" name={selected.roleId === "burson" ? "burson" : selected.roleId === "admin" ? "accounts" : "activities"} /></span><h2 className="display-title mt-3 text-xl">Acceso de colaborador</h2><strong className="mt-1 block text-sm">{selected.name}</strong><p className="text-[0.6875rem] text-ink-muted">{roles[selected.roleId].label}{selected.bursonLinked ? " especial · encargos Burson" : ""}</p><p className="mt-4 text-xs text-ink-muted">Ingresa tu clave personal para continuar</p></div><div className="mt-5" key={selected.accountId}><LoginForm initialUser={selected.user} /></div><p className="mt-4 border-t border-line pt-4 text-center text-[0.6875rem] text-ink-muted">▣ &nbsp; Acceso seguro y privado</p></Card>
  </main>;
}
