/* Empaqueta copias idénticas de los PNG revisados; nunca sobrescribe. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {createRequire}=require('node:module'),{pathToFileURL,fileURLToPath}=require('node:url');
const root=path.dirname(__dirname),repo=path.dirname(root),source=path.join(__dirname,'borrador-03'),target=path.join(root,'png');
const {chromium}=createRequire(path.join(repo,'frontend/package.json'))('playwright');
const sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
if(fs.existsSync(target))throw Error('Carpeta PNG existente: no sobrescribir');
const report=JSON.parse(fs.readFileSync(path.join(source,'verificacion.json'),'utf8'));
if(report.results.length!==16)throw Error('Se esperan 16 PNG');
fs.mkdirSync(target);
for(const r of report.results){const src=path.join(source,r.name+'.png'),dst=path.join(target,r.name+'.png');if(sha(src)!==r.hash)throw Error('Cambió el PNG revisado: '+r.name);fs.copyFileSync(src,dst,fs.constants.COPYFILE_EXCL);if(sha(dst)!==r.hash)throw Error('Copia diferente');}
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{const tests=[];for(const width of [1366,390]){const ctx=await browser.newContext({viewport:{width,height:900}});await ctx.setOffline(true);let blocked=0;await ctx.route('**/*',r=>{if(r.request().url().startsWith('file:'))return r.continue();blocked++;return r.abort();});const p=await ctx.newPage();await p.goto(pathToFileURL(path.join(root,'GALERIA.html')).href);await p.evaluate(async()=>{document.querySelectorAll('img').forEach(i=>i.loading='eager');await Promise.all([...document.images].map(i=>i.decode()));});const result=await p.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,images:document.images.length,broken:[...document.images].filter(i=>!i.naturalWidth).length,links:[...document.querySelectorAll('a[href]')].map(a=>a.href).filter(h=>!h.includes('#'))}));for(const href of result.links)if(!fs.existsSync(fileURLToPath(href)))throw Error('Enlace inexistente: '+href);if(result.images!==16||result.broken||result.scrollWidth>width)throw Error('Galería inválida');tests.push({...result,blocked});await ctx.close();}fs.writeFileSync(path.join(root,'VERIFICACION.json'),JSON.stringify({note:'Pruebas solo de maquetas offline y galería; no validan la aplicación.',pngCount:16,identicalCopies:true,source:'auxiliar/borrador-03',files:report.results.map(({name,hash,width,height})=>({name,hash,width,height})),gallery:tests},null,2),{flag:'wx'});console.log('16 PNG copiados con SHA256 idéntico. Galería PASS escritorio y móvil.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
