/* Contenido ficticio y HTML estático de diseño; nunca importa datos de Sistema R. */
const icons={activities:'<path d="M4 8h16v11H4zM4 8l2-4h14l-2 4M7 4l2 4m3-4 2 4m3-4 2 4"/>',calendar:'<rect height="16" rx="1" width="18" x="3" y="5"/><path d="M7 3v4m10-4v4M3 10h18"/>',complete:'<rect height="16" rx="1" width="16" x="4" y="4"/><path d="m8 12 3 3 6-7"/>',location:'<path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',message:'<path d="M4 4h16v12H9l-5 4V4Zm4 4h8m-8 4h5"/>',link:'<path d="m10 13.5 4-4M8.5 16.5 7 18a3.5 3.5 0 0 1-5-5l3-3a3.5 3.5 0 0 1 5 0M15.5 7.5 17 6a3.5 3.5 0 0 1 5 5l-3 3a3.5 3.5 0 0 1-5 0"/>',accounts:'<circle cx="8" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M2.5 20a5.5 5.5 0 0 1 11 0m1-5.5A5 5 0 0 1 21.5 19"/>',trash:'<path d="M4 7h16M9 3h6l1 4H8l1-4Zm-2 4 1 14h10l1-14M10 11v6m4-6v6"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m15.5 15.5 5 5"/>'};
icons.list='<rect x="4" y="3" width="16" height="18" rx="1"/><path d="M8 8h8M8 12h8M8 16h5"/>';
const icon=n=>'<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(icons[n]||icons.activities)+'</svg>';
const button=(text,primary=false,full=false)=>`<button type="button" class="btn ${primary?'primary':''} ${full?'full':''}" tabindex="-1">${text}</button>`;
const pill=(status)=>`<span class="pill ${status==='Entregada'?'done':status==='En proceso'?'work':''}">${status==='Programada'?'○':status==='En proceso'?'◐':'●'} ${status}</span>`;
const badge=n=>`<span class="message-badge"><i></i>${n} ${n===1?'nuevo':'nuevos'}</span>`;
const title=(label,name,sub,action='')=>`<div class="page-head"><div><p class="label">${label}</p><h1 class="section-title">${name}</h1><p>${sub}</p></div>${action}</div>`;
const journeys=(items)=>items.map(([day,place])=>`<div class="journey">${icon('calendar')}<strong>${day}</strong><span>${place}</span></div>`).join('');
const scenes=[
 {id:'panel-actividades',title:'Mi panel · actividades Aunor',nav:'Mi panel'},
 {id:'entrega-pendiente',title:'Detalle · antes de confirmar',nav:'Mi panel'},
 {id:'entrega-confirmada',title:'Detalle · confirmación registrada',nav:'Mi panel'},
 {id:'lo-acordado',title:'Lo acordado · servicios y trabajos',nav:'Lo acordado'},
 {id:'reemplazo',title:'Reemplazo · original, sustituto y evidencia',nav:'Lo acordado'},
 {id:'admin-respuesta-reemplazo',title:'Admin · responder y registrar reemplazo',nav:'Mi panel',admin:true},
 {id:'calendario',title:'Mi panel · calendario anual conservado',nav:'Mi panel'},
 {id:'mensajes',title:'Mensajes · conversaciones por actividad',nav:'Mensajes'},
];
function shell(scene,body,mobile){
 const nav=scene.admin?[['Mi panel','activities'],['Burson','accounts'],['Cuentas','accounts'],['Histórico','calendar'],['Papelera','trash']]:[['Mi panel','activities'],['Lo acordado','complete'],['Mensajes','message']];
 const links=nav.map(([name,ic])=>`<a href="#" aria-disabled="true" class="${scene.nav===name?'selected':''}">${icon(ic)}<span>${mobile&&scene.admin?(name==='Mi panel'?'Panel':name==='Papelera'?'Bajas':name):name}</span></a>`).join('');
 return `<header class="mock-header technical-surface"><div class="brand">CONTROL DE ACTIVIDADES<small>RHINO AUDIOVISUALES</small></div><div class="identity"><div class="avatar">${scene.admin?'MA':'AU'}</div><div class="account-name"><strong>${scene.admin?'Marco Admin':'Aunor'}</strong><small>${scene.admin?'Admin':'Acceso compartido'}</small></div><button class="exit">${mobile?'Salir':'Cerrar sesión'}</button></div></header><div class="mock-layout"><nav class="mock-sidebar technical-surface" ${scene.admin?'':'data-client-nav'}>${links}</nav><main class="mock-main app-surface"><div class="demo"><b>MAQUETA · EJEMPLOS FICTICIOS</b><span>${scene.admin?'Vista Admin':'Vista Aunor · cuenta compartida'} · sin datos reales ni acciones activas</span></div>${body}<p class="footnote">Propuesta visual para aprobación · fechas de ejemplo en 2026; no indican vigencia contractual.</p></main></div><nav class="mock-bottom" ${scene.admin?'':'data-client-nav'}>${links}</nav>`;
}
function activity({id,type='Grabación',name,status,dates,relation='Cobertura foto/video · 2.2',state,unlinked=false,messages=0}){
 return `<article class="card"><div class="activity-top ${type==='Edición'?'edit':''}"><div class="row"><span class="label type ${type==='Edición'?'edit':''}">${type} · ${id}</span>${pill(status)}</div><h2>${name}</h2></div><div class="card-body">${journeys(dates)}<div class="card-state">${state}</div></div><div class="card-foot"><span class="contract-tag ${unlinked?'unlinked':''}">${relation}</span>${messages?badge(messages):'<span class="small muted">Sin mensajes nuevos</span>'}</div><div class="card-foot" style="background:white">${button('Ver actividad →')}<span class="small muted">Publicada para Aunor</span></div></article>`;
}
function panel(){return title('ESPACIO AUNOR','Tus actividades','Días, lugares, entregas y conversaciones con Rhino.')+`<div class="tools"><div class="tabs"><span class="active">Actividades</span><span>Calendario anual</span></div><div class="search">${icon('search')}Buscar por nombre o código</div>${button('Todas las categorías ⌄')}</div><div class="notice"><div><strong>Hay respuestas nuevas de Rhino</strong><p class="small muted">Revisa cada conversación dentro de su actividad.</p></div><span class="link">Ver mensajes →</span></div><div class="cards">`+[
 {id:'GR-021',name:'Entrevistas en ruta',status:'Entregada',dates:[['16 jun.','Caseta Norte'],['18 jun.','Puesto Central']],state:'<b>Entrega:</b> pendiente de tu revisión. El trabajo ya está entregado.',messages:1},
 {id:'ED-009',type:'Edición',name:'Video de seguridad vial',status:'En proceso',dates:[['21–23 jun.','Edición remota']],relation:'Seguridad vial · 2.2',state:'<b>Entrega:</b> el material todavía no se ha publicado.',messages:2},
 {id:'GR-025',name:'Registro de señalización',status:'Entregada',dates:[['16 jun.','Tramo Sur']],relation:'Por relacionar',unlinked:true,state:'Es un trabajo de Aunor. <b>Falta asociarlo a un servicio.</b>'},
 {id:'GR-026',name:'Visita técnica de campo',status:'Programada',dates:[['8 sept.','Base Alto Norte']],state:'<b>Planificación publicada.</b> Jornadas aún por realizar.'}
 ].map(activity).join('')+`</div><p class="footnote">“Por relacionar” no oculta el trabajo: solo indica que falta su referencia en Lo acordado.</p>`;}
function summary(){return `<article class="card summary"><div class="hero technical-surface"><p class="label">GRABACIÓN · GR-021</p><h2>Entrevistas en ruta</h2><p>Cobertura de testimonios en dos jornadas y lugares.</p>${pill('Entregada')}</div><div class="metadata"><div><p class="label">DÍAS DE TRABAJO</p><b>16 y 18 de junio de 2026</b></div><div><p class="label">RELACIÓN</p><b>Cobertura foto/video · cláusula 2.2</b></div></div><section class="section-body"><p class="label">PLANIFICACIÓN PUBLICADA</p><h3 class="section-title">Jornadas y lugares</h3>${journeys([['16 jun.','Caseta Norte'],['18 jun.','Puesto Central']])}</section><section class="section-body"><p class="label">MATERIAL ENTREGADO</p><h3 class="section-title">Entrega E-021 · versión 1</h3><p>Entrevistas-ruta-v1.mp4<br><span class="small">Publicada el 22 jun., 10:00 · ejemplo</span></p><div class="gap-top">${button(icon('link')+'Abrir material ↗',true)}</div><p class="small">Entrega identificada para que tu confirmación se refiera a este material.</p></section></article>`;}
function chat(admin=false){return `<article class="card external-chat span-all" style="grid-column:1/-1"><header class="chat-head"><div class="row"><div><p class="label cyan">CONVERSACIÓN EXTERNA · GR-021</p><h2 class="section-title">${admin?'Conversación con Aunor':'Conversación con Rhino'}</h2></div>${admin?'<span class="small muted">Hilo externo</span>':badge(1)}</div><p>Solo Aunor y Admin. Este hilo corresponde a Entrevistas en ruta.</p></header><div class="messages"><div class="message"><header><strong>Aunor · cuenta compartida</strong><time>${admin?'11 jun. · 16:40':'22 jun. · 10:15'}</time></header><p>${admin?'Como comentamos en la llamada, el taller no se realizará. Quedamos atentos al registro de las entrevistas en su lugar.':'¿El enlace incluye las entrevistas de las dos jornadas?'}</p></div><div class="message rhino"><header><strong>Admin · Rhino</strong><time>${admin?'19 jun. · 09:15':'22 jun. · 10:25'}</time></header><p>${admin?'Estoy registrando el original, su motivo y las entrevistas como sustituto. Cuando publique la relación R-03, podrán revisarla y confirmarla expresamente.':'Sí. La entrega E-021 incluye Caseta Norte y Puesto Central. Puedes revisar el material desde el botón de entrega.'}</p></div></div><div class="composer"><div class="fake-input">${admin?'Escribir respuesta para Aunor…':'Escribir un comentario sobre esta actividad…'}</div>${button(admin?'Enviar respuesta':'Enviar comentario',true)}<p class="footnote">Los comentarios no confirman entregas ni reemplazos automáticamente.</p></div></article>`;}
function confirmDelivery(confirmed){return `<aside class="card confirm"><div class="pad"><p class="label cyan">CONFIRMACIÓN DE ENTREGA</p><h2 class="section-title">${confirmed?'Confirmación registrada':'Revisar esta entrega'}</h2><div class="box"><span class="label cyan">ENTREGA E-021 · VERSIÓN 1</span><strong>Entrevistas en ruta</strong><p class="small muted">Entrevistas-ruta-v1.mp4<br>22 jun. · 10:00</p></div>${confirmed?`<div class="stamp gap-top"><b>Entrega confirmada por Aunor</b>Cuenta compartida Aunor<small>22 jun. 2026 · 11:10</small><small>Objeto confirmado: E-021 · versión 1</small></div><p class="confirmation-caption">No hay una confirmación pendiente para esta entrega.</p><div class="box gap-top"><strong>El trabajo sigue Entregada.</strong><p class="small muted">La confirmación se registra por separado; no cambia su ejecución.</p></div>`:`<p class="confirmation-caption"><b>Pendiente de revisión por Aunor.</b><br>Revisa el material antes de confirmar.</p><div class="checkbox"><i>✓</i><span>He revisado E-021 · versión 1 y confirmo esta entrega en nombre de Aunor.</span></div>${button('Confirmar esta entrega',true,true)}<p class="confirmation-caption">Se registrará como <b>Aunor · cuenta compartida</b>, no como una persona identificada.</p>`}<p class="confirmation-caption"><b>Esto no aprueba pagos</b> ni confirma un reemplazo o cambio contractual.</p></div></aside>`;}
function detail(confirmed){return title('FICHA DE ACTIVIDAD · SOLO INFORMACIÓN PUBLICADA','Detalle de actividad',confirmed?'Escena posterior · misma entrega, confirmación ya registrada.':'Escena previa · el material está entregado y espera tu revisión.',button('← Volver a actividades'))+`<div class="two-col detail-scene">${summary()}${confirmDelivery(confirmed)}${chat()}</div>`;}
const services=['Cobertura fotográfica y audiovisual','Videos para redes sociales','Micronews internos','Videos de resumen anual','Videos de fiesta de fin de año','Videos de campañas internas','Videos sociales y ambientales','Videos de seguridad vial','Videos de voluntariado','Postproducción de resumen OSITRAN','Webinars','Spots radiales'];
function agreed(){return title('ESPACIO AUNOR · REFERENCIA CONTRACTUAL','Lo acordado','Los servicios previstos y el trabajo que se relaciona con ellos.')+`<div class="notice"><div><strong>Una lista sencilla, sin porcentajes de cumplimiento</strong><p class="small muted">Referencia: cláusula 2.2 del contrato aportado. Las cantidades y equivalencias no se resuelven en esta vista.</p></div></div><div class="service-layout"><section class="card pad"><p class="label cyan">LISTA SIMPLIFICADA DE SERVICIOS</p><h2 class="section-title" style="margin-top:7px">Qué está previsto</h2>${services.map((s,i)=>`<div class="service" data-service>${icon('list')}<div><b>${s}</b><small>Referencia contractual: cláusula 2.2${i===0?' · Ver trabajos relacionados →':''}</small></div></div>`).join('')}<p class="footnote">Nombres abreviados para lectura. El texto firmado se conserva como referencia; esta lista no lo modifica.</p></section><div class="stack"><section class="card pad"><p class="label cyan">SERVICIO SELECCIONADO · 2.2</p><h2 class="section-title" style="margin-top:7px">Cobertura foto/video</h2><div class="box gap-top"><p class="label">ORIGINAL · GR-014</p><strong>Taller de seguridad vial</strong><p class="small muted">No se realizó · evento cancelado por Aunor, según llamada registrada.</p></div><p class="link" style="text-align:center;padding:9px">↓ Relación de reemplazo R-03</p><div class="box"><p class="label cyan">SUSTITUTO · GR-021</p><strong>Entrevistas en ruta</strong><p class="small muted">16 y 18 jun. · Caseta Norte / Puesto Central</p></div><div class="stamp gap-top"><b>Reemplazo confirmado por Aunor</b><small>Cuenta compartida · 20 jun., 14:00</small><small>Se confirma la relación R-03, no una equivalencia económica.</small></div><div class="gap-top">${button('Ver original, sustituto y evidencia →',false,true)}</div></section><section class="card pad"><p class="label cyan">TRABAJO VISIBLE DE AUNOR</p><h2 class="section-title" style="margin-top:7px">Por relacionar</h2><div class="box gap-top"><span class="label">GR-025 · GRABACIÓN</span><strong>Registro de señalización</strong><p class="small muted">16 jun. · Tramo Sur</p><p class="small">Todavía no tiene un servicio contractual asociado.</p></div><p class="footnote">El trabajo y su entrega siguen visibles. No se descartan por faltar esta relación.</p><div class="gap-top">${button('Ver actividad →')}</div></section><p class="footnote">Lo realizado, la confirmación de entrega y el reemplazo son registros diferentes.</p></div></div>`;}
function originalPair(){return `<div class="replacement"><div class="record original"><p class="label">ORIGINAL · GR-014</p><h3>Taller de seguridad vial</h3><p>12 jun. 2026 · Base Norte</p><div class="reason"><b>No se realizó</b><p>El evento fue cancelado por Aunor, según la llamada registrada por Admin.</p></div></div><span class="replace-arrow">→</span><div class="record substitute"><p class="label cyan">SUSTITUTO · GR-021</p><h3>Entrevistas en ruta</h3><p>16 jun. · Caseta Norte<br>18 jun. · Puesto Central</p><div class="reason"><b>Trabajo realizado</b><p>Su entrega y confirmación se consultan por separado.</p></div></div></div>`;}
function replacement(){return title('LO ACORDADO · COBERTURA FOTO/VIDEO','Original y reemplazo','Relación R-03 · ambos trabajos permanecen registrados.',button('← Volver a Lo acordado'))+`<div class="two-col"><div class="stack"><section class="card pad"><h2 class="section-title" style="margin-bottom:20px">Lo previsto y lo realizado</h2>${originalPair()}<p class="footnote">Esta relación no define cantidades equivalentes ni un importe a pagar.</p></section><section class="card pad"><p class="label cyan">EVIDENCIA DEL ACUERDO</p><h2 class="section-title" style="margin-top:7px">Llamada registrada</h2><dl class="fact-list"><div><dt>Medio y fecha</dt><dd>Llamada · 11 jun., 16:30</dd></div><div><dt>Solicitante declarado</dt><dd>Ejecutivo de Aunor, según lo informado por Admin.</dd></div><div><dt>Registrado por</dt><dd>Admin · Rhino · 19 jun., 09:20</dd></div></dl><div class="box gap-top"><strong>Resumen de la llamada · ejemplo</strong><p>Se comunicó la cancelación del taller y se pidió registrar entrevistas en ruta en su lugar.</p></div><div class="gap-top">${button(icon('link')+'Ver nota de llamada ↗')}</div><p class="footnote">La nota documenta el relato del Admin. No acredita una identidad personal ni sustituye la confirmación de Aunor.</p></section></div><aside class="card confirm"><div class="pad"><p class="label cyan">CONFIRMACIÓN DEL REEMPLAZO</p><h2 class="section-title">Relación confirmada</h2><div class="box"><span class="label">OBJETO DE LA CONFIRMACIÓN</span><strong>R-03 · GR-014 → GR-021</strong><p>Taller de seguridad vial → Entrevistas en ruta</p></div><div class="stamp gap-top"><b>Confirmado por Aunor</b>Cuenta compartida Aunor<small>20 jun. 2026 · 14:00</small></div><div class="box gap-top"><strong>Declaración registrada</strong><p>“Confirmamos que GR-021 se registra en reemplazo de GR-014.”</p></div><p class="confirmation-caption">No hay una confirmación pendiente para esta relación.</p><p class="confirmation-caption"><b>No equivale a aprobación de pagos</b>, equivalencia económica ni confirmación de la entrega del sustituto.</p></div></aside></div>`;}
function field(name,value,full=false){return `<div class="field ${full?'full':''}"><b>${name}</b><div class="field-value">${value}</div></div>`;}
function admin(){return title('FICHA DE ACTIVIDAD · GESTIÓN ADMIN','Acuerdo y respuesta a Aunor','Dentro del detalle existente · la planificación y ejecución no cambian.')+`<div class="two-col"><article class="card"><div class="admin-context technical-surface"><p class="label">GR-021 · GRABACIÓN · CLIENTE AUNOR</p><h2>Entrevistas en ruta</h2></div><div class="step"><div class="step-title"><span class="step-num">1</span>Registrar lo acordado por llamada</div><div class="fields">${field('Canal de origen','Llamada')}${field('Fecha del contacto','11 jun. 2026 · 16:30')}${field('Solicitante declarado','Ejecutivo de Aunor, según la llamada',true)}${field('Registrado por','Admin · Rhino · 19 jun., 09:20',true)}</div><p class="footnote">El solicitante es un dato declarado; el registro administrativo no es una confirmación de Aunor.</p></div><div class="step"><div class="step-title"><span class="step-num">2</span>Relacionar original y sustituto</div><div class="fields">${field('Actividad original','GR-014 · Taller de seguridad vial')}${field('Actividad sustituta','GR-021 · Entrevistas en ruta')}${field('Motivo de no realización','Evento cancelado por Aunor, según llamada registrada.',true)}${field('Servicio de referencia','Cobertura foto/video · cláusula 2.2',true)}${field('Evidencia del acuerdo','Nota de llamada · 11 jun., 16:30',true)}</div><p class="footnote">Se conservan las dos actividades. No se calcula una equivalencia ni se cambia el estado de sus entregas.</p></div><div class="step"><div class="step-title"><span class="step-num">3</span>Revisar antes de publicar</div><div class="box"><strong>R-03 · GR-014 → GR-021</strong><p class="small muted">La confirmación de Aunor quedará pendiente después de publicar este registro.</p></div><div class="gap-top">${button('Publicar registro para Aunor',true,true)}</div><p class="footnote">Publicar documenta la propuesta. No confirma por el cliente ni aprueba pagos.</p></div></article><aside class="card confirm"><div class="pad"><p class="label cyan">VISTA PREVIA · CLIENTE</p><h2 class="section-title">Qué verá Aunor</h2><div class="box"><strong>Original conservado</strong><p class="small muted">GR-014 · no realizado<br>Motivo y llamada registrada.</p></div><div class="box gap-top"><strong>Sustituto identificado</strong><p class="small muted">GR-021 · días y lugares<br>Evidencia de la relación R-03.</p></div><div class="stamp gap-top"><b>Pendiente de confirmación por Aunor</b><small>Después de publicar, el cliente podrá revisar esta relación.</small></div><p class="confirmation-caption">Admin no confirma en nombre de la cuenta Aunor.</p></div></aside></div><div class="admin-chat"><div class="tabs" style="display:inline-flex;margin-bottom:12px"><span class="active">Conversación con Aunor</span><span>Conversación interna</span></div>${chat(true)}</div>`;}
const monthNames=['ENERO','FEBRERO','MARZO','ABRIL','MAYO','JUNIO','JULIO','AGOSTO','SEPTIEMBRE','OCTUBRE','NOVIEMBRE','DICIEMBRE'];
function month(m){let cells='';const offset=(new Date(Date.UTC(2026,m,1)).getUTCDay()+6)%7;for(let i=0;i<offset;i++)cells+='<span></span>';for(let d=1;d<=new Date(Date.UTC(2026,m+1,0)).getUTCDate();d++){let selected=m===5&&(d===16||d===18);let marked=selected||(m===8&&d===8);cells+=`<span class="day ${marked?'marked':''} ${selected?'chosen':''}">${d}${m===5&&d===16?'<b class="total">2</b>':''}</span>`;}return `<section class="month" data-month="${m+1}"><h3>${monthNames[m]}${m===5?'<span class="month-total">2</span>':m===8?'<span class="month-total">1</span>':''}</h3><div class="week">${['L','M','X','J','V','S','D'].map(d=>'<span>'+d+'</span>').join('')}</div><div class="days">${cells}</div></section>`;}
function calendar(){return title('ESPACIO AUNOR · MI PANEL','Calendario de actividades','La misma vista anual, limitada a tus actividades publicadas.')+`<div class="tools"><div class="tabs"><span>Actividades</span><span class="active">Calendario anual</span></div>${button('Grabación ⌄')}</div><div class="calendar-wrap"><section class="calendar-main"><div class="calendar-title"><div><p class="label cyan">JORNADAS DE AUNOR · EJEMPLO</p><h1 class="section-title" style="margin-top:6px">Histórico 2026</h1><p class="small muted" style="margin-top:10px">Todas las actividades de grabación del año</p></div><div class="year"><span>‹</span><b>2026</b><span>›</span></div></div><div class="legend"><span><i class="dot"></i>Grabación</span><span class="muted">3 registros de ejemplo</span></div><p class="small muted" style="font-size:11px;margin-top:8px">Color = categoría. Número oscuro = actividades en ese día.</p><div class="mobile-cal-link"><b>16 de junio · 2 actividades</b><br>GR-021 · Caseta Norte<br>GR-025 · Tramo Sur · Por relacionar<br><span class="link">Ver actividades de este día →</span></div><div class="months">${monthNames.map((_,m)=>month(m)).join('')}</div></section><aside class="calendar-detail"><p class="label cyan">16 DE JUNIO · 2 ACTIVIDADES</p><div class="choice selected"><b>GR-021 · Entrevistas en ruta</b><small>Caseta Norte · seleccionada</small></div><div class="choice"><b>GR-025 · Registro de señalización</b><small>Tramo Sur · Por relacionar</small></div><div style="margin-top:24px">${pill('Entregada')}</div><p class="label cyan" style="margin-top:20px">GRABACIÓN · GR-021</p><h2 class="section-title">Entrevistas en ruta</h2><p class="small muted">Una actividad, dos jornadas y lugares.</p>${journeys([['16 jun.','Caseta Norte'],['18 jun.','Puesto Central']])}<div class="box gap-top"><span class="label">ENTREGA</span><strong>Pendiente de revisión de Aunor</strong><p class="small muted">El trabajo ya está entregado.</p></div><div class="gap-top">${button('Ver entrega y conversación →',true,true)}</div></aside></div>`;}
function inbox(){return title('ESPACIO AUNOR','Mensajes','Cada conversación pertenece a una actividad. Admin responde por Rhino.')+`<div class="tools"><div class="tabs"><span class="active">Todos</span><span>Con mensajes nuevos</span></div><div class="search">${icon('search')}Buscar actividad</div></div><div class="card">`+[
 ['GR-021 · GRABACIÓN','Entrevistas en ruta','Admin · 22 jun., 10:25','Sí. La entrega incluye las dos jornadas de entrevistas.',1],
 ['ED-009 · EDICIÓN','Video de seguridad vial','Admin · 22 jun., 09:40','Estamos trabajando en la edición de las escenas publicadas.',2],
 ['GR-025 · GRABACIÓN','Registro de señalización · Por relacionar','Aunor · 21 jun., 16:10','Ya podemos abrir el enlace del material. Gracias.',0]
 ].map(([id,name,date,msg,n])=>`<article class="inbox-row"><span class="bubble-icon">${icon('message')}</span><div><div class="row"><p class="label">${id}</p>${n?badge(n):'<span class="small muted">Sin nuevos</span>'}</div><h2 style="font-size:22px">${name}</h2><p><b>${date}</b><br>${msg}</p></div>${button('Abrir hilo →')}</article>`).join('')+`</div><div class="read-note"><b>Un acceso compartido, una lectura compartida.</b><br>Los avisos indican lo que aún no abrió la cuenta Aunor; no comprueban qué ejecutivo lo leyó.</div><p class="footnote">Un mensaje como “gracias” no confirma una entrega. La confirmación se hace expresamente dentro de la actividad.</p>`;}
function build(scene,mobile){const body=scene.id==='panel-actividades'?panel():scene.id==='entrega-pendiente'?detail(false):scene.id==='entrega-confirmada'?detail(true):scene.id==='lo-acordado'?agreed():scene.id==='reemplazo'?replacement():scene.id==='admin-respuesta-reemplazo'?admin():scene.id==='calendario'?calendar():inbox();return shell(scene,body,mobile);}
module.exports={scenes,build};
