"use client";

import { useCallback, useMemo, useSyncExternalStore } from "react";
import { accountsCookieName, defaultAccounts, parseAccounts, serializeAccountsCookie, type Account, type AccountFields } from "@/lib/accounts";

export const accountStoreKey = "rhino:cuentas-simuladas:v1"; const changedEvent = "rhino:cuentas-simuladas-cambio"; const seedSnapshot = JSON.stringify(defaultAccounts); const serverSnapshot = () => seedSnapshot;
export function readAccounts(storage: Pick<Storage, "getItem">) { return parseAccounts(storage.getItem(accountStoreKey)); }
function save(storage: Pick<Storage, "setItem">, accounts: Account[]) { storage.setItem(accountStoreKey, JSON.stringify(accounts)); document.cookie = `${accountsCookieName}=${encodeURIComponent(serializeAccountsCookie(accounts))}; path=/; SameSite=Lax`; window.dispatchEvent(new Event(changedEvent)); }
function update(storage: Pick<Storage, "getItem" | "setItem">, id: string, actor: string, action: string, change: (account: Account, current: Account[]) => Account | string) { const current = readAccounts(storage); const found = current.find((account) => account.id === id); if (!found) return { ok: false as const, error: "La cuenta no existe." }; const result = change(found, current); if (typeof result === "string") return { ok: false as const, error: result }; const now = new Date().toISOString(); const next = { ...result, updatedAt: now, updatedBy: actor, history: [{ action, actor, moment: now }, ...result.history] }; save(storage, current.map((account) => account.id === id ? next : account)); return { ok: true as const, account: next }; }
export function upsertAccount(storage: Pick<Storage, "getItem" | "setItem">, fields: AccountFields, actor: string, id?: string) { const current = readAccounts(storage); if (!fields.name.trim() || !fields.username.trim() || !fields.password.trim() || fields.roleIds.length === 0) return { ok: false as const, error: "Completa nombre, usuario, clave y al menos un rol." }; if (current.some((account) => account.id !== id && account.username.toLowerCase() === fields.username.trim().toLowerCase())) return { ok: false as const, error: "Ese usuario ya está en uso." }; const previous = id ? current.find((account) => account.id === id) : undefined; const now = new Date().toISOString(); const accountId = previous?.id ?? `account-${Date.now().toString(36)}`; const next: Account = { id: accountId, name: fields.name.trim(), initials: fields.name.trim().split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase(), username: fields.username.trim().toLowerCase(), password: fields.password, roleIds: fields.roleIds, active: previous?.active ?? true, createdAt: previous?.createdAt ?? now, updatedAt: now, updatedBy: actor, history: [{ action: previous ? "Cuenta editada" : "Cuenta creada", actor, moment: now }, ...(previous?.history ?? [])] }; save(storage, [next, ...current.filter((account) => account.id !== accountId)]); return { ok: true as const, account: next }; }
export function toggleAccount(storage: Pick<Storage, "getItem" | "setItem">, id: string, actor: string) { return update(storage, id, actor, "Estado de cuenta cambiado", (account, current) => { if (account.active && account.roleIds.includes("supervision") && current.filter((item) => item.active && item.roleIds.includes("supervision")).length === 1) return "No puedes desactivar la última cuenta administrativa."; return { ...account, active: !account.active }; }); }
export function useAccounts() { const subscribe = useCallback((notify: () => void) => { const onStorage = (event: StorageEvent) => { if (event.key === accountStoreKey) notify(); }; window.addEventListener("storage", onStorage); window.addEventListener(changedEvent, notify); return () => { window.removeEventListener("storage", onStorage); window.removeEventListener(changedEvent, notify); }; }, []); const snapshot = useCallback(() => window.localStorage.getItem(accountStoreKey) ?? seedSnapshot, []); const raw = useSyncExternalStore(subscribe, snapshot, serverSnapshot); return useMemo(() => parseAccounts(raw), [raw]); }
