"use client";

import { useCallback, useMemo, useSyncExternalStore } from "react";
import type { BursonStatus } from "@/components/burson-status-pill";

export const bursonStoreKey = "rhino:solicitudes-burson:v1";
const changedEvent = "rhino:solicitudes-burson-cambio";
export type BursonComment = { id: string; text: string; author: string; createdAt: string; editedAt?: string; editedBy?: string; deletedAt?: string; deletedBy?: string };
export type BursonHistory = { status: BursonStatus; actor: string; moment: string };
export type BursonRequest = { id: string; request: string; date: string; responsible: string; material: string; status: BursonStatus; rhinoPending: string; bursonPending: string; deliveryDate: string; approvalDate: string; comments: BursonComment[]; history: BursonHistory[]; updatedAt: string; deletedAt?: string; deletedBy?: string };
export type BursonFields = Pick<BursonRequest, "request" | "date" | "responsible" | "material" | "status" | "rhinoPending" | "bursonPending" | "deliveryDate" | "approvalDate">;

const seed: BursonRequest[] = [
  { id: "campana-invierno", request: "Campaña de seguridad en invierno", date: "2026-08-16", responsible: "Coordinación", material: "Selección de fotografías de vía", status: "En proceso", rhinoPending: "Enviar selección final", bursonPending: "Validar textos de campaña", deliveryDate: "", approvalDate: "", comments: [], history: [{ status: "En proceso", actor: "Coordinación", moment: "2026-08-16T10:00:00-05:00" }], updatedAt: "2026-08-16T10:00:00-05:00" },
  { id: "nota-desvios", request: "Nota sobre desvíos temporales", date: "2026-08-13", responsible: "Sin asignar", material: "Enlace a tomas de señalización", status: "Solicitado", rhinoPending: "Asignar responsable", bursonPending: "Confirmar fecha de publicación", deliveryDate: "", approvalDate: "", comments: [], history: [{ status: "Solicitado", actor: "Coordinación", moment: "2026-08-13T09:00:00-05:00" }], updatedAt: "2026-08-13T09:00:00-05:00" },
  { id: "resumen-julio", request: "Resumen audiovisual de julio", date: "2026-08-02", responsible: "Coordinación", material: "Enlace al resumen mensual", status: "Entregado", rhinoPending: "Sin pendientes", bursonPending: "Dar conformidad al material", deliveryDate: "2026-08-17", approvalDate: "", comments: [{ id: "comment-resumen", text: "Material compartido para revisión.", author: "Coordinación", createdAt: "2026-08-17T14:00:00-05:00" }], history: [{ status: "Entregado", actor: "Coordinación", moment: "2026-08-17T14:00:00-05:00" }], updatedAt: "2026-08-17T14:00:00-05:00" },
];
const seedSnapshot = JSON.stringify(seed); const serverSnapshot = () => seedSnapshot;
export function parseBursonStore(raw: string | null): BursonRequest[] { if (!raw) return seed; try { const value: unknown = JSON.parse(raw); return Array.isArray(value) ? value as BursonRequest[] : seed; } catch { return seed; } }
export function readBursonRequests(storage: Pick<Storage, "getItem">) { return parseBursonStore(storage.getItem(bursonStoreKey)); }
function save(storage: Pick<Storage, "setItem">, requests: BursonRequest[]) { storage.setItem(bursonStoreKey, JSON.stringify(requests)); window.dispatchEvent(new Event(changedEvent)); }
function slug(value: string) { return `${value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 36) || "solicitud"}-${Date.now().toString(36)}`; }
function update(storage: Pick<Storage, "getItem" | "setItem">, id: string, change: (request: BursonRequest) => BursonRequest | string) { const current = readBursonRequests(storage); const found = current.find((item) => item.id === id); if (!found) return { ok: false as const, error: "La solicitud no existe." }; const result = change(found); if (typeof result === "string") return { ok: false as const, error: result }; save(storage, current.map((item) => item.id === id ? result : item)); return { ok: true as const, request: result }; }

export function upsertBursonRequest(storage: Pick<Storage, "getItem" | "setItem">, fields: BursonFields, actor: string, id?: string) {
  if (!fields.request.trim() || !fields.date || !fields.material.trim()) return { ok: false as const, error: "Completa solicitud, fecha y material." };
  const current = readBursonRequests(storage); const previous = id ? current.find((item) => item.id === id) : undefined; const now = new Date().toISOString(); const requestId = previous?.id ?? slug(fields.request);
  const history = previous ? (previous.status === fields.status ? previous.history : [{ status: fields.status, actor, moment: now }, ...previous.history]) : [{ status: fields.status, actor, moment: now }];
  const next: BursonRequest = { ...fields, id: requestId, responsible: fields.responsible || "Sin asignar", comments: previous?.comments ?? [], history, updatedAt: now };
  save(storage, [next, ...current.filter((item) => item.id !== requestId)]); return { ok: true as const, request: next };
}
export function deleteBursonRequest(storage: Pick<Storage, "getItem" | "setItem">, id: string, actor: string) { return update(storage, id, (request) => request.deletedAt ? "La solicitud ya fue eliminada." : { ...request, deletedAt: new Date().toISOString(), deletedBy: actor }); }
export function addBursonComment(storage: Pick<Storage, "getItem" | "setItem">, id: string, text: string, actor: string) { return update(storage, id, (request) => !text.trim() ? "Escribe un comentario." : { ...request, comments: [{ id: `comment-${Date.now().toString(36)}`, text: text.trim(), author: actor, createdAt: new Date().toISOString() }, ...request.comments], updatedAt: new Date().toISOString() }); }
export function editBursonComment(storage: Pick<Storage, "getItem" | "setItem">, requestId: string, commentId: string, text: string, actor: string) { return update(storage, requestId, (request) => { const comment = request.comments.find((item) => item.id === commentId); if (!comment || comment.deletedAt) return "El comentario no existe."; if (!text.trim()) return "El comentario no puede quedar vacío."; const now = new Date().toISOString(); return { ...request, comments: request.comments.map((item) => item.id === commentId ? { ...item, text: text.trim(), editedAt: now, editedBy: actor } : item), updatedAt: now }; }); }
export function deleteBursonComment(storage: Pick<Storage, "getItem" | "setItem">, requestId: string, commentId: string, actor: string) { return update(storage, requestId, (request) => { const comment = request.comments.find((item) => item.id === commentId); if (!comment || comment.deletedAt) return "El comentario no existe."; const now = new Date().toISOString(); return { ...request, comments: request.comments.map((item) => item.id === commentId ? { ...item, deletedAt: now, deletedBy: actor } : item), updatedAt: now }; }); }
export function useBursonRequests() { const subscribe = useCallback((notify: () => void) => { const onStorage = (event: StorageEvent) => { if (event.key === bursonStoreKey) notify(); }; window.addEventListener("storage", onStorage); window.addEventListener(changedEvent, notify); return () => { window.removeEventListener("storage", onStorage); window.removeEventListener(changedEvent, notify); }; }, []); const snapshot = useCallback(() => window.localStorage.getItem(bursonStoreKey) ?? seedSnapshot, []); const raw = useSyncExternalStore(subscribe, snapshot, serverSnapshot); return useMemo(() => parseBursonStore(raw), [raw]); }
